language: python
python:
  - "3.9"

services:
  - mysql

before_install:
  - pip install pycodestyle
  - mysql -e 'CREATE DATABASE IF NOT EXISTS develop;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

install:
  - pip install pipenv
  - pipenv install --dev
  - flask db upgrade

script:
  - python -m pytest tests/
  - coverage run --source="src/" -m pytest
  - coverage report -m
  - pycodestyle src/ --ignore=E722,E501,E402

