version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t smart_docker_repo .
      - docker tag smart_docker_repo:latest 835894273863.dkr.ecr.us-east-2.amazonaws.com/smart_docker_repo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 835894273863.dkr.ecr.us-east-2.amazonaws.com/smart_docker_repo:latest