version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t smart_meter .
      - docker tag smart_meter:1 835894273863.dkr.ecr.eu-north-1.amazonaws.com/smart_meter
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 835894273863.dkr.ecr.eu-north-1.amazonaws.com/smart_meter