"""init

Revision ID: 58432b3d9c85
Revises: 
Create Date: 2021-05-15 20:30:34.349770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58432b3d9c85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=254), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('homes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('smart_meters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_name', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('home_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['home_id'], ['homes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('ApplianceMetaData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_value', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('smart_meters_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['smart_meters_id'], ['smart_meters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ApplianceMetaData')
    op.drop_table('smart_meters')
    op.drop_table('homes')
    op.drop_table('users')
    # ### end Alembic commands ###
