"""add home_model UniqueConstraint

Revision ID: 8588f799a59b
Revises: 58432b3d9c85
Create Date: 2021-05-16 15:29:35.070048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8588f799a59b'
down_revision = '58432b3d9c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_component_commit', 'homes', ['home_name', 'user_id'])
    op.alter_column('users', 'uuid',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'uuid',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.drop_constraint('unique_component_commit', 'homes', type_='unique')
    # ### end Alembic commands ###
