"""add indexes

Revision ID: dac843ff6e20
Revises: 1fc6cfcd3ee8
Create Date: 2021-05-20 11:40:43.052153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac843ff6e20'
down_revision = '1fc6cfcd3ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ApplianceMetaData_date'), 'ApplianceMetaData', ['date'], unique=False)
    op.drop_index('uuid', table_name='homes')
    op.drop_index('uuid_2', table_name='homes')
    op.create_index(op.f('ix_homes_uuid'), 'homes', ['uuid'], unique=True)
    op.drop_index('uuid', table_name='smart_meters')
    op.drop_index('uuid_2', table_name='smart_meters')
    op.create_index(op.f('ix_smart_meters_uuid'), 'smart_meters', ['uuid'], unique=True)
    op.drop_index('username', table_name='users')
    op.drop_index('username_2', table_name='users')
    op.drop_index('uuid', table_name='users')
    op.drop_index('uuid_2', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('uuid_2', 'users', ['uuid'], unique=False)
    op.create_index('uuid', 'users', ['uuid'], unique=False)
    op.create_index('username_2', 'users', ['username'], unique=False)
    op.create_index('username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_smart_meters_uuid'), table_name='smart_meters')
    op.create_index('uuid_2', 'smart_meters', ['uuid'], unique=False)
    op.create_index('uuid', 'smart_meters', ['uuid'], unique=False)
    op.drop_index(op.f('ix_homes_uuid'), table_name='homes')
    op.create_index('uuid_2', 'homes', ['uuid'], unique=False)
    op.create_index('uuid', 'homes', ['uuid'], unique=False)
    op.drop_index(op.f('ix_ApplianceMetaData_date'), table_name='ApplianceMetaData')
    # ### end Alembic commands ###
